// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProviderOptimizerService.Infrastructure.Persistence;

#nullable disable

namespace ProviderOptimizerService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OptimizerDbContext))]
    [Migration("20260223200650_SyncModel_Providers_NoCapabilities")]
    partial class SyncModel_Providers_NoCapabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProviderOptimizerService.Domain.Model.AssistanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssistanceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("assistance_id");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.ComplexProperty<Dictionary<string, object>>("Constraints", "ProviderOptimizerService.Domain.Model.AssistanceRequest.Constraints#Constraints", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("MaxEtaMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("max_eta_minutes");

                            b1.Property<string>("PreferredNetworks")
                                .HasColumnType("text")
                                .HasColumnName("preferred_networks");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Location", "ProviderOptimizerService.Domain.Model.AssistanceRequest.Location#GeoPoint", b1 =>
                        {
                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Lng")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssistanceId")
                        .IsUnique();

                    b.ToTable("assistance_requests", (string)null);
                });

            modelBuilder.Entity("ProviderOptimizerService.Domain.Model.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CostPerKm")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_per_km");

                    b.Property<double>("CoverageRadiusKm")
                        .HasColumnType("double precision")
                        .HasColumnName("coverage_radius_km");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.ComplexProperty<Dictionary<string, object>>("CurrentLocation", "ProviderOptimizerService.Domain.Model.Provider.CurrentLocation#GeoPoint", b1 =>
                        {
                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Lng")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");
                        });

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("ProviderOptimizerService.Infrastructure.Persistence.Configurations.ProviderCapability", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.HasKey("ProviderId", "ServiceType");

                    b.ToTable("provider_capabilities", (string)null);
                });

            modelBuilder.Entity("ProviderOptimizerService.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("ProviderOptimizerService.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ProviderOptimizerService.Infrastructure.Persistence.Configurations.ProviderCapability", b =>
                {
                    b.HasOne("ProviderOptimizerService.Domain.Model.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
